# -*- coding: utf-8 -*-
"""Modul.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/117nHsP0Iz2SMyT7_P6MgrUSoHMGpPWlT
"""

import numpy as np


class Transaction():
  
  def __init__(self):
    nama = input('Masukan nama anda : ')
    self.data_item = dict() # nama sebagai index
    self.id = nama[0].upper() + '-' + str(np.random.randint(1,10000))

  def tambah_item(self, nama, jumlah, harga): # fungsi untuk menambah item belanjaan
    self.data_item[nama.lower()] = [jumlah, harga]

  def update_nama(self, namaLama, namaBaru): # fungsi untuk memperbarui nama item
    self.data_item[namaBaru.lower()] = self.data_item[namaLama.lower()]
    del self.data_item[namaLama.lower()]

  def update_jumlah(self, nama, jumlahBaru): # fungsi untuk memperbarui jumlah item
    self.data_item[nama][0] = jumlahBaru

  def update_harga(self, nama, hargaBaru): # fungsi untuk memperbarui harga item
    self.data_item[nama][1] = hargaBaru

  def check_data_item(self): # fungsi untuk mengecek data item
    return self.data_item

  def reset_belanjaan(self): # fungsi untuk menghapus seluruh belanjaan
    self.data_item.clear()
    print('semua item berhasil didelete')

  def delete_item(self, nama): # fungsi untuk menghapus item belanjaan
    self.data_item.pop(nama.lower())

  def check_order(self): # fungsi untuk mengecek input belanjaan customer
    for i in list(self.data_item.keys()):
      if type(self.data_item[i][0]) != int:
        print(f'terdapat kesalahan input data pada item {i}')
        print(self.data_item[i])
        break
      elif type(self.data_item[i][1]) != int:
        print(f'terdapat kesalahan input data pada item {i}')
        print(self.data_item[i])
        break
      else:
        print(f'pesanan pada item {i} sudah benar')
        print(self.data_item[i])

  def discount_checkout(self): # fungsi untuk mengecek total harga keseluruhan dan diskon belanjaan customer
    total_harga = 0
    for i in list(self.data_item.keys()):
      total_harga += (int(self.data_item[i][0])*int(self.data_item[i][1]) )
      
    if total_harga > 500_000:
      final_harga = total_harga * (1 - 0.1)
      print(f'Selamat! Anda mendapat diskon sebesar 10%.')
      print(f'Item yang anda beli adalah : {self.data_item}')
      print(f'Total belanja dengan id transaksi {self.id} sebelum diskon adalah Rp. {total_harga:.0f} dan setelah diskon adalah Rp. {final_harga:.0f}')
    elif total_harga > 300_000:
      final_harga = total_harga * (1 - 0.08)
      print('Selamat! Anda mendapat diskon sebesar 8%.')
      print(f'Item yang anda beli adalah : {self.data_item}')
      print(f'Total belanja dengan id transaksi {self.id} sebelum diskon adalah Rp. {total_harga:.0f} dan setelah diskon adalah Rp. {final_harga:.0f}')
    elif total_harga > 200_000:
      final_harga = total_harga * (1 - 0.05)
      print('Selamat! Anda mendapat diskon sebesar 5%.')
      print(f'Item yang anda beli adalah : {self.data_item}')
      print(f'Total belanja dengan id transaksi {self.id} sebelum diskon adalah Rp. {total_harga:.0f} dan setelah diskon adalah Rp. {final_harga:.0f}')
    else:
      final_harga = total_harga
      print('Maaf anda beum mendapatkan diskon')
      print(f'Item yang anda beli adalah : {self.data_item}')
      print(f'Total belanja dengan id transaksi {self.id} adalah Rp. {self.total_harga:.0f}')